[project]
name = "ctp-swig-build"
version = "0.0.1"
description = "一键实现自动编译CTP C++接口为Python接口"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "meson-python>=0.18.0",
    "mypy>=1.18.1",
]
